name: Covasim CI workflow
on: [push, pull_request]

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        python-version: [ '3.7' ]
    name: Install and test
    steps:
      - name: Set repo owner env variable
        shell: python
        run: print("::set-env name=GITHUB_OWNER::{}".format('${{github.repository}}'.split('/')[0]))
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Checkout synthpops
        uses: actions/checkout@v2
        with:
            repository: ${{ env.GITHUB_OWNER }}/synthpops
            # Checking out a private repo requires a Personal Access Token (PAT).  To create one, follow the instructions at:
            #   https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line#creating-a-token
            # The account creating the PAT needs to have access to the private repo, and the PAT should be scoped to "repo".
            # To add the PAT as a Secret, usable by this workflow, follow the instructions at:
            #   https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets
            # NOTE: The secret must be named "GitHub_PAT"
            token: ${{ secrets.GitHub_PAT }}
            path: ./synthpops
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Covasim
        run: python setup.py develop
      - name: Install synthpops
        working-directory: ./synthpops
        run: python setup.py develop
      - name: Run tests
        working-directory: ./tests
        run: |
          pip install pytest
          pytest test_*.py unittests/*tests.py --junitxml=test-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: test_results
          path: tests/test-results.xml